import streamlit as st
import openai
from typing import Dict, Any, List

def get_section_from_llm(api_key: str, prompt: str) -> str:
    openai.api_key = api_key
    try:
        response = openai.ChatCompletion.create(
            model="gpt-4o-mini",  # Updated to use the correct model name
            messages=[
                {"role": "system", "content": "You are an expert business plan writer."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=500,
            temperature=0.7
        )
        return response.choices[0].message['content'].strip()
    except Exception as e:
        st.error(f"Error calling OpenAI API: {str(e)}")
        return ""

# The rest of the functions (validate_section, create_feedback_prompt, generate_business_plan) remain the same

def main():
    st.title("AI-Powered Business Plan Generator (using GPT-4o-mini)")

    st.write("""
    This app uses GPT-4o-mini to generate a comprehensive business plan. 
    Please enter your OpenAI API key to begin.
    """)

    api_key = st.text_input("Enter your OpenAI API key", type="password")

    if api_key:
        if st.button("Generate Business Plan"):
            progress_bar = st.progress(0)
            status_text = st.empty()

            try:
                business_plan = generate_business_plan(api_key, progress_bar, status_text)
                
                st.success("Business Plan Generated Successfully!")
                
                for section, content in business_plan.items():
                    with st.expander(f"{section}"):
                        st.write(content)
                
                # Option to download the business plan
                st.download_button(
                    label="Download Business Plan",
                    data=str(business_plan),
                    file_name="business_plan.txt",
                    mime="text/plain"
                )
                
            except Exception as e:
                st.error(f"An error occurred: {str(e)}")
    else:
        st.warning("Please enter your OpenAI API key to use this app.")

    st.write("""
    **Disclaimer**: This business plan is generated by AI (GPT-4o-mini) and should be used as a starting point only. 
    Please review, modify, and expand upon this plan to ensure it accurately reflects your specific business idea and goals.
    """)

if __name__ == "__main__":
    main()
